apiVersion: v1
kind: Service
metadata:
  name: rgame
spec:
  selector:
    # We want our service to load balance across 
    # all pods with the label as app=game
    app: rgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
